#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MobileRolloutManager.Resource", IsApplication=true)]

namespace MobileRolloutManager
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ZXing.Mobile.Resource.Id.contentFrame = global::MobileRolloutManager.Resource.Id.contentFrame;
			global::ZXing.Mobile.Resource.Layout.zxingscanneractivitylayout = global::MobileRolloutManager.Resource.Layout.zxingscanneractivitylayout;
			global::ZXing.Mobile.Resource.Layout.zxingscannerfragmentlayout = global::MobileRolloutManager.Resource.Layout.zxingscannerfragmentlayout;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010010
			public const int ambientEnabled = 2130771984;
			
			// aapt resource value: 0x7f010014
			public const int buttonSize = 2130771988;
			
			// aapt resource value: 0x7f010001
			public const int cameraBearing = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int cameraTargetLat = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int cameraTargetLng = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int cameraTilt = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int cameraZoom = 2130771973;
			
			// aapt resource value: 0x7f010013
			public const int circleCrop = 2130771987;
			
			// aapt resource value: 0x7f010015
			public const int colorScheme = 2130771989;
			
			// aapt resource value: 0x7f010012
			public const int imageAspectRatio = 2130771986;
			
			// aapt resource value: 0x7f010011
			public const int imageAspectRatioAdjust = 2130771985;
			
			// aapt resource value: 0x7f010006
			public const int liteMode = 2130771974;
			
			// aapt resource value: 0x7f010000
			public const int mapType = 2130771968;
			
			// aapt resource value: 0x7f010016
			public const int scopeUris = 2130771990;
			
			// aapt resource value: 0x7f010007
			public const int uiCompass = 2130771975;
			
			// aapt resource value: 0x7f01000f
			public const int uiMapToolbar = 2130771983;
			
			// aapt resource value: 0x7f010008
			public const int uiRotateGestures = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int uiScrollGestures = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int uiTiltGestures = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int uiZoomControls = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int uiZoomGestures = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int useViewLifecycle = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public const int zOrderOnTop = 2130771982;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060008
			public const int common_action_bar_splitter = 2131099656;
			
			// aapt resource value: 0x7f060011
			public const int common_google_signin_btn_text_dark = 2131099665;
			
			// aapt resource value: 0x7f060009
			public const int common_google_signin_btn_text_dark_default = 2131099657;
			
			// aapt resource value: 0x7f06000b
			public const int common_google_signin_btn_text_dark_disabled = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int common_google_signin_btn_text_dark_focused = 2131099660;
			
			// aapt resource value: 0x7f06000a
			public const int common_google_signin_btn_text_dark_pressed = 2131099658;
			
			// aapt resource value: 0x7f060012
			public const int common_google_signin_btn_text_light = 2131099666;
			
			// aapt resource value: 0x7f06000d
			public const int common_google_signin_btn_text_light_default = 2131099661;
			
			// aapt resource value: 0x7f06000f
			public const int common_google_signin_btn_text_light_disabled = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int common_google_signin_btn_text_light_focused = 2131099664;
			
			// aapt resource value: 0x7f06000e
			public const int common_google_signin_btn_text_light_pressed = 2131099662;
			
			// aapt resource value: 0x7f060013
			public const int common_plus_signin_btn_text_dark = 2131099667;
			
			// aapt resource value: 0x7f060000
			public const int common_plus_signin_btn_text_dark_default = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int common_plus_signin_btn_text_dark_disabled = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int common_plus_signin_btn_text_dark_focused = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int common_plus_signin_btn_text_dark_pressed = 2131099649;
			
			// aapt resource value: 0x7f060014
			public const int common_plus_signin_btn_text_light = 2131099668;
			
			// aapt resource value: 0x7f060004
			public const int common_plus_signin_btn_text_light_default = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int common_plus_signin_btn_text_light_disabled = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int common_plus_signin_btn_text_light_focused = 2131099655;
			
			// aapt resource value: 0x7f060005
			public const int common_plus_signin_btn_text_light_pressed = 2131099653;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int addButton = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int barcode = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int camera = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int common_full_open_on_phone = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int common_google_signin_btn_icon_dark = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int common_google_signin_btn_icon_dark_disabled = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int common_google_signin_btn_icon_dark_focused = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int common_google_signin_btn_icon_dark_normal = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int common_google_signin_btn_icon_dark_pressed = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int common_google_signin_btn_icon_light = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int common_google_signin_btn_icon_light_disabled = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int common_google_signin_btn_icon_light_focused = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int common_google_signin_btn_icon_light_normal = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int common_google_signin_btn_icon_light_pressed = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int common_google_signin_btn_text_dark = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_google_signin_btn_text_dark_disabled = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_google_signin_btn_text_dark_focused = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_google_signin_btn_text_dark_normal = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_google_signin_btn_text_dark_pressed = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int common_google_signin_btn_text_light = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int common_google_signin_btn_text_light_disabled = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int common_google_signin_btn_text_light_focused = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int common_google_signin_btn_text_light_normal = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int common_google_signin_btn_text_light_pressed = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int common_ic_googleplayservices = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int common_plus_signin_btn_icon_dark = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int common_plus_signin_btn_icon_dark_disabled = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int common_plus_signin_btn_icon_dark_focused = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int common_plus_signin_btn_icon_dark_normal = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int common_plus_signin_btn_icon_dark_pressed = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int common_plus_signin_btn_icon_light = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int common_plus_signin_btn_icon_light_disabled = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int common_plus_signin_btn_icon_light_focused = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int common_plus_signin_btn_icon_light_normal = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int common_plus_signin_btn_icon_light_pressed = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int common_plus_signin_btn_text_dark = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int common_plus_signin_btn_text_dark_disabled = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int common_plus_signin_btn_text_dark_focused = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int common_plus_signin_btn_text_dark_normal = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int common_plus_signin_btn_text_dark_pressed = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int common_plus_signin_btn_text_light = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int common_plus_signin_btn_text_light_disabled = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int common_plus_signin_btn_text_light_focused = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int common_plus_signin_btn_text_light_normal = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int common_plus_signin_btn_text_light_pressed = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int dial = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int edit = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int hand = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int Icon = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int images = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int Log = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int map = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int menu = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int notes = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int person = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int RolloutManager = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int signoff = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int SiteHistory = 2130837561;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070016
			public const int Add = 2131165206;
			
			// aapt resource value: 0x7f070020
			public const int AddSim = 2131165216;
			
			// aapt resource value: 0x7f070055
			public const int Address1 = 2131165269;
			
			// aapt resource value: 0x7f070058
			public const int Address2 = 2131165272;
			
			// aapt resource value: 0x7f07005b
			public const int Address3 = 2131165275;
			
			// aapt resource value: 0x7f07005a
			public const int AddressText = 2131165274;
			
			// aapt resource value: 0x7f070015
			public const int AssetBack = 2131165205;
			
			// aapt resource value: 0x7f07001d
			public const int Assets = 2131165213;
			
			// aapt resource value: 0x7f07002f
			public const int BarCodeBtn = 2131165231;
			
			// aapt resource value: 0x7f07003e
			public const int Client = 2131165246;
			
			// aapt resource value: 0x7f070049
			public const int ContactPerson = 2131165257;
			
			// aapt resource value: 0x7f07003a
			public const int DirectionsToSite = 2131165242;
			
			// aapt resource value: 0x7f07003c
			public const int EditDetails = 2131165244;
			
			// aapt resource value: 0x7f070024
			public const int ImagesList = 2131165220;
			
			// aapt resource value: 0x7f07001b
			public const int InstBack = 2131165211;
			
			// aapt resource value: 0x7f070031
			public const int ItemDescription = 2131165233;
			
			// aapt resource value: 0x7f070030
			public const int ItemNameT = 2131165232;
			
			// aapt resource value: 0x7f07004f
			public const int Latitude = 2131165263;
			
			// aapt resource value: 0x7f070052
			public const int Longitude = 2131165266;
			
			// aapt resource value: 0x7f07002c
			public const int MyButton = 2131165228;
			
			// aapt resource value: 0x7f070022
			public const int Notes = 2131165218;
			
			// aapt resource value: 0x7f07004c
			public const int PersonTel = 2131165260;
			
			// aapt resource value: 0x7f07003d
			public const int Project = 2131165245;
			
			// aapt resource value: 0x7f070037
			public const int Quantity = 2131165239;
			
			// aapt resource value: 0x7f070039
			public const int Save = 2131165241;
			
			// aapt resource value: 0x7f070034
			public const int Serial = 2131165236;
			
			// aapt resource value: 0x7f07001f
			public const int SignOff = 2131165215;
			
			// aapt resource value: 0x7f07003f
			public const int Site = 2131165247;
			
			// aapt resource value: 0x7f070043
			public const int SiteId = 2131165251;
			
			// aapt resource value: 0x7f07001c
			public const int SiteName = 2131165212;
			
			// aapt resource value: 0x7f070042
			public const int SiteStatus = 2131165250;
			
			// aapt resource value: 0x7f070046
			public const int SiteTel = 2131165254;
			
			// aapt resource value: 0x7f07003b
			public const int StartInstall = 2131165243;
			
			// aapt resource value: 0x7f070027
			public const int Text = 2131165223;
			
			// aapt resource value: 0x7f070005
			public const int adjust_height = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int adjust_width = 2131165190;
			
			// aapt resource value: 0x7f070010
			public const int allsitesBack = 2131165200;
			
			// aapt resource value: 0x7f070018
			public const int allsitesBack3 = 2131165208;
			
			// aapt resource value: 0x7f07000a
			public const int auto = 2131165194;
			
			// aapt resource value: 0x7f070061
			public const int btn_allSites = 2131165281;
			
			// aapt resource value: 0x7f070019
			public const int btngps = 2131165209;
			
			// aapt resource value: 0x7f070066
			public const int contentFrame = 2131165286;
			
			// aapt resource value: 0x7f07000b
			public const int dark = 2131165195;
			
			// aapt resource value: 0x7f07005e
			public const int dial = 2131165278;
			
			// aapt resource value: 0x7f070000
			public const int hybrid = 2131165184;
			
			// aapt resource value: 0x7f070007
			public const int icon_only = 2131165191;
			
			// aapt resource value: 0x7f070026
			public const int imageView1 = 2131165222;
			
			// aapt resource value: 0x7f070023
			public const int imgBack = 2131165219;
			
			// aapt resource value: 0x7f070021
			public const int issue = 2131165217;
			
			// aapt resource value: 0x7f07000c
			public const int light = 2131165196;
			
			// aapt resource value: 0x7f07002d
			public const int linearLayout1 = 2131165229;
			
			// aapt resource value: 0x7f070063
			public const int list = 2131165283;
			
			// aapt resource value: 0x7f070065
			public const int list2 = 2131165285;
			
			// aapt resource value: 0x7f070014
			public const int list3 = 2131165204;
			
			// aapt resource value: 0x7f070017
			public const int listAssets = 2131165207;
			
			// aapt resource value: 0x7f070062
			public const int map = 2131165282;
			
			// aapt resource value: 0x7f07001a
			public const int mapF = 2131165210;
			
			// aapt resource value: 0x7f07002e
			public const int mapback = 2131165230;
			
			// aapt resource value: 0x7f070001
			public const int none = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int normal = 2131165186;
			
			// aapt resource value: 0x7f070060
			public const int notes = 2131165280;
			
			// aapt resource value: 0x7f07002b
			public const int password = 2131165227;
			
			// aapt resource value: 0x7f07005f
			public const int person = 2131165279;
			
			// aapt resource value: 0x7f07001e
			public const int photoProof = 2131165214;
			
			// aapt resource value: 0x7f070025
			public const int relativeLayout1 = 2131165221;
			
			// aapt resource value: 0x7f070003
			public const int satellite = 2131165187;
			
			// aapt resource value: 0x7f070011
			public const int searchView1 = 2131165201;
			
			// aapt resource value: 0x7f070008
			public const int standard = 2131165192;
			
			// aapt resource value: 0x7f07000d
			public const int tableLayout1 = 2131165197;
			
			// aapt resource value: 0x7f07005c
			public const int tableLayout2 = 2131165276;
			
			// aapt resource value: 0x7f07000e
			public const int tableRow1 = 2131165198;
			
			// aapt resource value: 0x7f070056
			public const int tableRow10 = 2131165270;
			
			// aapt resource value: 0x7f070059
			public const int tableRow11 = 2131165273;
			
			// aapt resource value: 0x7f070044
			public const int tableRow13 = 2131165252;
			
			// aapt resource value: 0x7f070047
			public const int tableRow14 = 2131165255;
			
			// aapt resource value: 0x7f07004a
			public const int tableRow15 = 2131165258;
			
			// aapt resource value: 0x7f07000f
			public const int tableRow2 = 2131165199;
			
			// aapt resource value: 0x7f070040
			public const int tableRow26 = 2131165248;
			
			// aapt resource value: 0x7f07005d
			public const int tableRow28 = 2131165277;
			
			// aapt resource value: 0x7f070012
			public const int tableRow3 = 2131165202;
			
			// aapt resource value: 0x7f070032
			public const int tableRow4 = 2131165234;
			
			// aapt resource value: 0x7f070035
			public const int tableRow5 = 2131165237;
			
			// aapt resource value: 0x7f070038
			public const int tableRow6 = 2131165240;
			
			// aapt resource value: 0x7f07004d
			public const int tableRow7 = 2131165261;
			
			// aapt resource value: 0x7f070050
			public const int tableRow8 = 2131165264;
			
			// aapt resource value: 0x7f070053
			public const int tableRow9 = 2131165267;
			
			// aapt resource value: 0x7f070004
			public const int terrain = 2131165188;
			
			// aapt resource value: 0x7f070013
			public const int textView1 = 2131165203;
			
			// aapt resource value: 0x7f070028
			public const int textView10 = 2131165224;
			
			// aapt resource value: 0x7f07002a
			public const int textView11 = 2131165226;
			
			// aapt resource value: 0x7f070033
			public const int textView12 = 2131165235;
			
			// aapt resource value: 0x7f070036
			public const int textView13 = 2131165238;
			
			// aapt resource value: 0x7f070045
			public const int textView14 = 2131165253;
			
			// aapt resource value: 0x7f070048
			public const int textView15 = 2131165256;
			
			// aapt resource value: 0x7f07004b
			public const int textView16 = 2131165259;
			
			// aapt resource value: 0x7f07004e
			public const int textView17 = 2131165262;
			
			// aapt resource value: 0x7f070051
			public const int textView18 = 2131165265;
			
			// aapt resource value: 0x7f070054
			public const int textView19 = 2131165268;
			
			// aapt resource value: 0x7f070064
			public const int textView2 = 2131165284;
			
			// aapt resource value: 0x7f070057
			public const int textView20 = 2131165271;
			
			// aapt resource value: 0x7f070041
			public const int textView26 = 2131165249;
			
			// aapt resource value: 0x7f070029
			public const int user = 2131165225;
			
			// aapt resource value: 0x7f070009
			public const int wide = 2131165193;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f050000
			public const int google_play_services_version = 2131034112;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AllSites = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Asets = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Direction = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int EditDetails = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Installation = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int LayoutSPhotos = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Main = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int MappedAssignedSites = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int NewAsset = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int NewImage = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int SiteDetails = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int SiteNotes = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int SiteRollout = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int Sites = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int zxingscanneractivitylayout = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int zxingscannerfragmentlayout = 2130903055;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040020
			public const int ApplicationName = 2130968608;
			
			// aapt resource value: 0x7f04001f
			public const int Hello = 2130968607;
			
			// aapt resource value: 0x7f040021
			public const int Menu = 2130968609;
			
			// aapt resource value: 0x7f040001
			public const int auth_google_play_services_client_facebook_display_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int auth_google_play_services_client_google_display_name = 2130968576;
			
			// aapt resource value: 0x7f040018
			public const int common_google_play_services_api_unavailable_text = 2130968600;
			
			// aapt resource value: 0x7f04000a
			public const int common_google_play_services_enable_button = 2130968586;
			
			// aapt resource value: 0x7f040009
			public const int common_google_play_services_enable_text = 2130968585;
			
			// aapt resource value: 0x7f040008
			public const int common_google_play_services_enable_title = 2130968584;
			
			// aapt resource value: 0x7f040007
			public const int common_google_play_services_install_button = 2130968583;
			
			// aapt resource value: 0x7f040005
			public const int common_google_play_services_install_text_phone = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int common_google_play_services_install_text_tablet = 2130968582;
			
			// aapt resource value: 0x7f040004
			public const int common_google_play_services_install_title = 2130968580;
			
			// aapt resource value: 0x7f040013
			public const int common_google_play_services_invalid_account_text = 2130968595;
			
			// aapt resource value: 0x7f040012
			public const int common_google_play_services_invalid_account_title = 2130968594;
			
			// aapt resource value: 0x7f040011
			public const int common_google_play_services_network_error_text = 2130968593;
			
			// aapt resource value: 0x7f040010
			public const int common_google_play_services_network_error_title = 2130968592;
			
			// aapt resource value: 0x7f040003
			public const int common_google_play_services_notification_ticker = 2130968579;
			
			// aapt resource value: 0x7f04001c
			public const int common_google_play_services_restricted_profile_text = 2130968604;
			
			// aapt resource value: 0x7f04001b
			public const int common_google_play_services_restricted_profile_title = 2130968603;
			
			// aapt resource value: 0x7f04001a
			public const int common_google_play_services_sign_in_failed_text = 2130968602;
			
			// aapt resource value: 0x7f040019
			public const int common_google_play_services_sign_in_failed_title = 2130968601;
			
			// aapt resource value: 0x7f040002
			public const int common_google_play_services_unknown_issue = 2130968578;
			
			// aapt resource value: 0x7f040015
			public const int common_google_play_services_unsupported_text = 2130968597;
			
			// aapt resource value: 0x7f040014
			public const int common_google_play_services_unsupported_title = 2130968596;
			
			// aapt resource value: 0x7f040016
			public const int common_google_play_services_update_button = 2130968598;
			
			// aapt resource value: 0x7f04000c
			public const int common_google_play_services_update_text = 2130968588;
			
			// aapt resource value: 0x7f04000b
			public const int common_google_play_services_update_title = 2130968587;
			
			// aapt resource value: 0x7f04000f
			public const int common_google_play_services_updating_text = 2130968591;
			
			// aapt resource value: 0x7f04000e
			public const int common_google_play_services_updating_title = 2130968590;
			
			// aapt resource value: 0x7f04000d
			public const int common_google_play_services_wear_update_text = 2130968589;
			
			// aapt resource value: 0x7f040017
			public const int common_open_on_phone = 2130968599;
			
			// aapt resource value: 0x7f04001d
			public const int common_signin_button_text = 2130968605;
			
			// aapt resource value: 0x7f04001e
			public const int common_signin_button_text_long = 2130968606;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] LoadingImageView = new int[] {
					2130771985,
					2130771986,
					2130771987};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			public static int[] MapAttrs = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984};
			
			// aapt resource value: 16
			public const int MapAttrs_ambientEnabled = 16;
			
			// aapt resource value: 1
			public const int MapAttrs_cameraBearing = 1;
			
			// aapt resource value: 2
			public const int MapAttrs_cameraTargetLat = 2;
			
			// aapt resource value: 3
			public const int MapAttrs_cameraTargetLng = 3;
			
			// aapt resource value: 4
			public const int MapAttrs_cameraTilt = 4;
			
			// aapt resource value: 5
			public const int MapAttrs_cameraZoom = 5;
			
			// aapt resource value: 6
			public const int MapAttrs_liteMode = 6;
			
			// aapt resource value: 0
			public const int MapAttrs_mapType = 0;
			
			// aapt resource value: 7
			public const int MapAttrs_uiCompass = 7;
			
			// aapt resource value: 15
			public const int MapAttrs_uiMapToolbar = 15;
			
			// aapt resource value: 8
			public const int MapAttrs_uiRotateGestures = 8;
			
			// aapt resource value: 9
			public const int MapAttrs_uiScrollGestures = 9;
			
			// aapt resource value: 10
			public const int MapAttrs_uiTiltGestures = 10;
			
			// aapt resource value: 11
			public const int MapAttrs_uiZoomControls = 11;
			
			// aapt resource value: 12
			public const int MapAttrs_uiZoomGestures = 12;
			
			// aapt resource value: 13
			public const int MapAttrs_useViewLifecycle = 13;
			
			// aapt resource value: 14
			public const int MapAttrs_zOrderOnTop = 14;
			
			public static int[] SignInButton = new int[] {
					2130771988,
					2130771989,
					2130771990};
			
			// aapt resource value: 0
			public const int SignInButton_buttonSize = 0;
			
			// aapt resource value: 1
			public const int SignInButton_colorScheme = 1;
			
			// aapt resource value: 2
			public const int SignInButton_scopeUris = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
